version: '3.8'
services:
  app:
    image: ghcr.io/drach-db/demo-personal-cabinet:dev
    ports:
      - "3000:3000"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    restart: unless-stopped